### ISSUE TITLE
wfMsg, wfMsgExt and wfMsgHtml are deprecated

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticWatchlist#10]
wfMessage to rule them all.

**Comment by kghbln** [comment]
The last [transgressor](https://github.com/SemanticMediaWiki/SemanticWatchlist/search?utf8=%E2%9C%93&q=wfMsgHtml)

**Comment by kghbln** [comment]
@JeroenDeDauw It will be cool if we get this (https://github.com/SemanticMediaWiki/SemanticWatchlist/issues/10#issuecomment-70750129) into 1.0 Just advise if this change is cool and I will do a pull request for it.

**Comment by JeroenDeDauw** [comment]
I've not used the MW i18n system for two years or so, hence I cannot tell if that is correct or not. Ping @Nikerabbit @siebrand

**Comment by kghbln** [comment]
@siebrand This is the resistor: https://github.com/SemanticMediaWiki/SemanticWatchlist/issues/10#issuecomment-70750129

**Comment by siebrand** [comment]
This:

 wfMsgHtml( 'swl-watchlist-pagincontrol', $wgLang->pipeList( array( $firstLink, $nextLink ) ), $wgLang->pipeList( $limitLinks ) )

Should be converted to wfMessage as:

 wfMessage( 'swl-watchlist-pagincontrol' )
  ->rawParams(
   $wgLang->pipeList( array( $firstLink, $nextLink ) )
   $wgLang->pipeList( $limitLinks )
  ->escaped()

This results in 'swl-watchlist-pagincontrol' being escaped, and the parameters being used as raw parameters. The solution suggested in the earlier comment, would have resulted in escaped links.

**Comment by kghbln** [comment]
Thank you very much! Well this is just a single comma difference in text but a big difference in result. Will revisit this to understand it better! Will do the change now. Great!

**Comment by siebrand** [comment]
Oh, wait. You did use rawParams. In that case, please ignore my semantically incorrect suggestion. You did do it correctly.

**Comment by kghbln** [comment]
Fast enough :)

**Comment by kghbln** [comment]
Thanks again @siebrand It took me a long time but with this pull request https://github.com/SemanticMediaWiki/SemanticWatchlist/pull/37 the migration is finally done for this extension.

**Comment by kghbln** [comment]
This was the last hold-up for https://github.com/SemanticMediaWiki/SemanticWatchlist/issues/36
