### ISSUE TITLE
Replace deprecated Hooks::run

### ISSUE THREAD

**Issue by umherirrender** [SemanticMediaWiki/SemanticWatchlist#101]
### Issue

The function `Hooks::run` is soft-deprecated and going to emit warnings, see 
https://phabricator.wikimedia.org/T335536

**Comment by paladox** [comment]
This was fixed with https://github.com/SemanticMediaWiki/SemanticWatchlist/commit/b22d83ca1f89d3cd96565ae27df49c4a40b65999.
