### ISSUE TITLE
Special:SpecialPages broken

### ISSUE THREAD

**Issue by ckoerner** [SemanticMediaWiki/SemanticWatchlist#32]
Trying to view Special:SpecialPages as a logged-in sysop I receive the following message:

    Fatal error: Call to a member function text() on a non-object in /var/www/html/w/extensions/SemanticWatchlist/specials/SpecialSemanticWatchlist.php on line 40

Line 40 reads:

 	public function getDescription() {
		return wfMessage( 'special-' . strtolower( $this->getName() )->text() );
	}

When visiting Special:SpecialPages as an unauthenticated user I do not receive this message (Most likely as the SemanticWatchlist pages are sysop only.

Commenting out the lines suggested in the discussion below seems to get around this issue, but I am not sure how that impacts functionality. 

http://www.mediawiki.org/wiki/Thread:Extension_talk:Semantic_Watchlist/Error_in_SpecialWatchlistConditions.php_and_SpecialSemanticWatchlist.php

**Comment by DestructionOfPlanetJupiter** [comment]
Appears to be fixed in 1.24 but persists in 1.25

**Comment by JeroenDeDauw** [comment]
@ckoerner is this solved for you?

@mwjames any thoughts about what @DestructionOfPlanetJupiter wrote?

**Comment by mwjames** [comment]
> any thoughts about what @DestructionOfPlanetJupiter wrote?

Not really and unless there is a stack trace or exception not much to go on.

**Comment by JeroenDeDauw** [comment]
Ok, let's close this now then. Can reopen if this is not fixed for @ckoerner. @DestructionOfPlanetJupiter can you create a dedicated issue for the problem you ran into?
