### ISSUE TITLE
Create 1.0 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticWatchlist#36]
Known blockers: none

**Comment by kghbln** [comment]
Go for it @JeroenDeDauw :)

**Comment by JeroenDeDauw** [comment]
Would still be nice if we could at least have a go at fixing the bugs. And it kinds sucks this thing can still not be installed via Composer. Just send a mail to the list asking for help with this. Let's see if that results in anything.

**Comment by mwjames** [comment]
> And it kinds sucks this thing can still not be installed via Composer

To make your life easier, https://packagist.org/packages/mediawiki/semantic-watchlist

**Comment by JeroenDeDauw** [comment]
\o/

**Comment by JeroenDeDauw** [comment]
Tag created

**Comment by kghbln** [comment]
\o/

**Comment by simison** [comment]
Thank you gentlemen!
