### ISSUE TITLE
Notification text&format not properly working

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticWatchlist#4]
Importing from https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/211

The notification e-mail of Semantic Watchlist has problems with non-ASCII-characters, example:

Eines oder mehrere der auf MSCRM beobachteten Attribute wurden vom Benutzer Wikiadmin am 25. Februar 2014 um 12:30 Uhr geÃ¤ndert. Diese und andere Ã„nderungen werden auf dieser semantischen Beobachtungsliste angezeigt.

Also the special message text if a monitored attribute changes to an expected vaule is never user (neither in the notification e-mail nor in the semantic watchlist page text).

**Comment by tosfos** [comment]
Does not appear to still be an issue. WikiTeq tested with non-ASCII characters (specifically some Chinese characters) for page name, property name, and property value, and all of the email notifications worked fine.
