### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by nogothenogo** [SemanticMediaWiki/SemanticWatchlist#44]
with this extension
when i edit a page and then press save then it jumps to a database error message on the edit page
without the extension
when i edit a page and then press save then i jumps to the edited page
in both cases the page appears edited.

some how it jumps to the wrong page or database error

there was a message about
SELECT group_id,group_name,group_categories,group_namespaces,group_properties,group_concepts,group_custom_texts FROM `swl_groups`
with the debug option

but now with out this extension all is fine again

**Comment by mwjames** [comment]
After you have installed `SWL` you need to run `maintenance/update.php` as explained in the extension documentation.

If for some reason you use `sqlite` then #43 is necessary.

**Comment by mwjames** [comment]
It is generally of great help to post whole stack trace (see swm.org@stack trace).

**Comment by JeroenDeDauw** [comment]
@nogothenogo what database are you using? And can you post the actual error message? If not, we can not act on this issue.
