### ISSUE TITLE
Non-Composer installation

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticWatchlist#48]
@mwjames am I seeing correctly that installation without Composer is no longer supported?

**Comment by mwjames** [comment]
> am I seeing correctly that installation without Composer is no longer supported?

I don't understand the question. If someone wants to use git s(he) is free to do so right?

**Comment by JeroenDeDauw** [comment]
Looks like you added new classes which are not registered with the MW loader or have a custom loader, hence require some autoloader using the definition from composer.json.

**Comment by mwjames** [comment]
Ahh, yes that's right classes in `src` follow PSR-4

**Comment by JeroenDeDauw** [comment]
Ok, I'll up the README then to clarity
