### ISSUE TITLE
TWN doc

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticWatchlist#49]
@kghbln on https://www.mediawiki.org/wiki/Extension:Semantic_Watchlist it says `No localisation updates are provided by translatewiki.net.`. Any idea how to get rid of that?

**Comment by kghbln** [comment]
Well, the respective template assumes that all extensions with their main repo on GitHub do not get these updates. In general this is correct but ...  Will have to tweak this one. Hold on...

**Comment by kghbln** [comment]
Somebody already tweaked the template. So [this was all that had to be done](https://www.mediawiki.org/w/index.php?title=Extension:Semantic_Watchlist&diff=prev&oldid=1386272)
