### ISSUE TITLE
Fatal error: Class 'SWL\HookRegistry' not found

### ISSUE THREAD

**Issue by simison** [SemanticMediaWiki/SemanticWatchlist#50]
I just updated to 1.0 via composer.phar and now I'm getting:
```
Fatal error: Class 'SWL\HookRegistry' not found in /var/www/public/wiki/extensions/SemanticWatchlist/SemanticWatchlist.php on line 143
```

Any pointers?

**Comment by JeroenDeDauw** [comment]
You did something wrong with the installation. The error indicates the autoloader is not build or not included. What exactly did you do to install the extension?

**Comment by mwjames** [comment]
You need to install SWL via `composer require` because classes in 'src' folder adhere PSR-4 and require the autoloader from Composer to invoke the classes upon loading.

**Comment by mwjames** [comment]
I'm not sure whether a `LocalSettings.php` entry (`require .../SemanticWatchlist/SemanticWatchlist.php`) could cause any confusion for the autoloader or not.

**Comment by simison** [comment]
Ah, we've got bigger project where MediaWiki is just one part, so we've got our root composer.json where I added this as a requirement. I'll try to run composer require in wiki folder, just a mo.

PS. Thanks for a super quick reply!

**Comment by JeroenDeDauw** [comment]
If you add the extension to the root composer.json and run composer update for it, then you do not need to bother with the extension folder at all. You do not need to run any commands in it, and you do not need to include anything from it.

**Comment by JeroenDeDauw** [comment]
@mwjames not sure either and to lazy to find out. After this there definitely should be no issue: #51

**Comment by simison** [comment]
Yepp, perfect. Works now, thanks!
