### ISSUE TITLE
PHP Fatal error:  Class 'SWL\HookRegistry' not found in /home/yyy/htdocs/w/extensions/SemanticWatchlist/SemanticWatchlist.php on line 143

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [SemanticMediaWiki/SemanticWatchlist#52]
PHP Fatal error:  Class 'SWL\HookRegistry' not found in /home/yyy/htdocs/w/extensions/SemanticWatchlist/SemanticWatchlist.php on line 143
PHP Stack trace:
PHP   1. {main}() /home/yyy/htdocs/w/maintenance/update.php:0
PHP   2. require_once() /home/yyy/htdocs/w/maintenance/update.php:206
PHP   3. require_once() /home/yyy/htdocs/w/maintenance/doMaintenance.php:97
PHP   4. call_user_func() /home/yyy/htdocs/w/includes/Setup.php:659
PHP   5. {closure:/home/yyy/htdocs/w/extensions/SemanticWatchlist/SemanticWatchlist.php:134-148}() /home/yyy/htdocs/w/includes/Setup.php:659

I downloaded the version from git and got this error once the update routine is started.

**Comment by JeroenDeDauw** [comment]
Dup of #50

@mwjames @kghbln Guess the docs are not clear enough

**Comment by DestructionOfPlanetJupiter** [comment]
I did not expect it to see there, as it had not been part of the packagist repository as of late. 

Checked and worked. Thanks

**Comment by kghbln** [comment]
The README appears no different to me than the ones for other extensions. However I added more reference to [Composer on mw.o](https://www.mediawiki.org/w/index.php?title=Extension%3ASemantic_Watchlist&diff=1389074&oldid=1386291). Everything else is a matter of habit, I guess.

**Comment by kghbln** [comment]
The README still had to be extended a bit https://github.com/SemanticMediaWiki/SemanticWatchlist/commit/7c91bb0e9bc8f94c09ef786483589d959d40814a
