### ISSUE TITLE
Verify MW < 1.21 compat has not been broken

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticWatchlist#53]
By https://gerrit.wikimedia.org/r/#/c/184675/

**Comment by mwjames** [comment]
Has been reverted with https://gerrit.wikimedia.org/r/#/c/189330/.

**Comment by JeroenDeDauw** [comment]
Now merged here dd9ec05965eb24aac885304b6cc136ac7558ff42

@umherirrender Please don't just merge things because you can without consulting the extension maintainers. Don't misunderstand me, your help is much appreciated.
