### ISSUE TITLE
Make PSR-0 compliant

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticWatchlist#6]

**Comment by mwjames** [comment]
Classes in `src` follow PSR-4 while remaining non-complaint classes can be found in the `api`, `includes`, and `specials` folder.

**Comment by JeroenDeDauw** [comment]
Cool :)

**Comment by tosfos** [comment]
PSR-4 compliance was added in b2e549d2edddc89864946a63b3c4d192ec2aa5b0. PSR-0 officially deprecated. Closing
