### ISSUE TITLE
Got explicit BEGIN from DatabaseBase::begin while atomic section(s) RenameuserSQL::rename are open.

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticWatchlist#66]
**Setup**

- MediaWiki 	1.27.0 (758cd9d) 22:24, 28. Jun. 2016
- Semantic MediaWiki	2.5.0-alpha (570a26b) 12:00, 8. Aug. 2016
- Semantic Watchlist	1.1.0 (df2732b) 08:18, 7. Jul. 2016
- Renameuser	– (615d761) 20:26, 10. Jun. 2016
- PHP 	5.6.24-0+deb8u1 (apache2handler)
- MariaDB 	10.0.26-MariaDB-1~jessie

**Issue**

Then trying to rename a user via "Special:Renameuser" I get the following excetion:

[f3fb92ad120ad89873c7fa53] /wiki/Sp%C3%A9cial:Renommer_utilisateur DBUnexpectedError from line 2585 of /.../includes/db/Database.php: Got explicit BEGIN from DatabaseBase::begin while atomic section(s) RenameuserSQL::rename are open.

**Backtrace**
```
#0 /.../extensions/SemanticWatchlist/src/TableUpdater.php(40): DatabaseBase->begin()
#1 /.../extensions/SemanticWatchlist/src/MediaWiki/Hooks/UserSaveOptions.php(75): SWL\TableUpdater->updateGroupIdsForUser(integer, array)
#2 /.../extensions/SemanticWatchlist/src/MediaWiki/Hooks/UserSaveOptions.php(68): SWL\MediaWiki\Hooks\UserSaveOptions->performUpdate(array)
#3 /.../extensions/SemanticWatchlist/src/HookRegistry.php(75): SWL\MediaWiki\Hooks\UserSaveOptions->execute()
#4 [internal function]: SWL\HookRegistry->SWL\{closure}(User, array)
#5 /.../includes/Hooks.php(195): call_user_func_array(Closure, array)
#6 /.../includes/user/User.php(5098): Hooks::run(string, array)
#7 /.../includes/user/User.php(3802): User->saveOptions()
#8 /.../includes/session/SessionManager.php(306): User->saveSettings()
#9 /.../extensions/Renameuser/RenameuserSQL.php(199): MediaWiki\Session\SessionManager->invalidateSessionsForUser(User)
#10 /.../extensions/Renameuser/specials/SpecialRenameuser.php(306): RenameuserSQL->rename()
#11 /.../includes/specialpage/SpecialPage.php(479): SpecialRenameuser->execute(NULL)
#12 /.../includes/specialpage/SpecialPageFactory.php(576): SpecialPage->run(NULL)
#13 /.../includes/MediaWiki.php(282): SpecialPageFactory::executePath(Title, RequestContext)
#14 /.../includes/MediaWiki.php(745): MediaWiki->performRequest()
#15 /.../includes/MediaWiki.php(519): MediaWiki->main()
#16 /.../index.php(43): MediaWiki->run()
#17 {main}
```

**Comment by mwjames** [comment]
> Got explicit BEGIN from DatabaseBase::begin while atomic section(s) RenameuserSQL::rename are open.

Doing a `begin`/`commit` [0] will most certainly break transactions in MW 1.27+ hence why SMW is doing [1].

Try to replace `->begin` with `->startAtomic( __METHOD__ )` and `->commit` with `->endAtomic( __METHOD__ )`

[0] https://github.com/SemanticMediaWiki/SemanticWatchlist/blob/master/src/TableUpdater.php#L40-L53

[1] https://www.semantic-mediawiki.org/wiki/Deferred_updates

**Comment by kghbln** [comment]
> Try to replace

Great, this was it! After getting atomic is was able to successfully rename a user. I will create a pull tomorrow.
