### ISSUE TITLE
Notification mail has HTML formatting issues with MediaWiki 1.27+

### ISSUE THREAD

**Issue by boboivancich** [SemanticMediaWiki/SemanticWatchlist#73]
Hi

I've noticed that notification mails are not properly created, with the current version of Mediawiki.

MediaWiki 1.27 changes to function UserMailer::send() dropped backwards compatibility with previous versions of this function, which had $replyto as the 5th argument and $contentType as the 6th.

As a result SWLEmailer::notifyUser(), when used with MediaWiki 1.27+, sends notification with incorrect MIME type.

In addition, the use on Html::element() to include the description of changes, breaks the HTML formatting, while using Html::rawElement() works correctly.

Both issues are addressed with https://github.com/SemanticMediaWiki/SemanticWatchlist/pull/72

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
@JeroenDeDauw What about a 1.1.1 release to get [this and translation updates](https://github.com/SemanticMediaWiki/SemanticWatchlist/compare/1.1.0...master) to the public?
