### ISSUE TITLE
Deprecations from MW 1.25 are causing trouble on Special:SemanticWatchlist

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticWatchlist#76]
![image](https://user-images.githubusercontent.com/43581/30453469-f4866bbc-9966-11e7-80a7-b631d9be7e9a.png)

When running under E_STRICT, deprecation notices can obscure the useful information on the page.

**Comment by kghbln** [comment]
Thanks for reporting and providing a patch.
