### ISSUE TITLE
SemanticWatchlist DB error

### ISSUE THREAD

**Issue by Hutchy68** [SemanticMediaWiki/SemanticWatchlist#91]
MW 1.31.6, requires semanticwatchlist -> ~1.0 loading with composer. All watchlist tables appear to be present, but this error appears on special page. Also, breaks users preferences, example... change of skin for a logged in user. Any ideas? 

Output of error:

```
[6460e77799b9c9363c319895] /wiki/Special:SemanticWatchlist Wikimedia\Rdbms\DBUnexpectedError from line 3692 of /home/mw-131/public_html/w/includes/libs/rdbms/database/Database.php: Wikimedia\Rdbms\Database::begin: Implicit transaction already active (from Wikimedia\Rdbms\Database::query (User::loadFromDatabase)).

Backtrace:

#0 /home/mw-131/public_html/w/extensions/SemanticWatchlist/src/TableUpdater.php(40): Wikimedia\Rdbms\Database->begin()
#1 /home/mw-131/public_html/w/extensions/SemanticWatchlist/src/MediaWiki/Hooks/UserSaveOptions.php(74): SWL\TableUpdater->updateGroupIdsForUser(integer, array)
#2 /home/mw-131/public_html/w/extensions/SemanticWatchlist/src/MediaWiki/Hooks/UserSaveOptions.php(68): SWL\MediaWiki\Hooks\UserSaveOptions->performUpdate(array)
#3 /home/mw-131/public_html/w/extensions/SemanticWatchlist/src/HookRegistry.php(75): SWL\MediaWiki\Hooks\UserSaveOptions->execute()
#4 /home/mw-131/public_html/w/includes/Hooks.php(177): SWL\HookRegistry->SWL\{closure}(User, array)
#5 /home/mw-131/public_html/w/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#6 /home/mw-131/public_html/w/includes/user/User.php(5516): Hooks::run(string, array)
#7 /home/mw-131/public_html/w/includes/user/User.php(4177): User->saveOptions()
#8 /home/mw-131/public_html/w/extensions/SemanticWatchlist/specials/SpecialSemanticWatchlist.php(159): User->saveSettings()
#9 /home/mw-131/public_html/w/extensions/SemanticWatchlist/specials/SpecialSemanticWatchlist.php(74): SpecialSemanticWatchlist->registerUserView(User)
#10 /home/mw-131/public_html/w/includes/specialpage/SpecialPage.php(565): SpecialSemanticWatchlist->execute(NULL)
#11 /home/mw-131/public_html/w/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#12 /home/mw-131/public_html/w/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#13 /home/mw-131/public_html/w/includes/MediaWiki.php(861): MediaWiki->performRequest()
#14 /home/mw-131/public_html/w/includes/MediaWiki.php(524): MediaWiki->main()
#15 /home/mw-131/public_html/w/index.php(42): MediaWiki->run()
#16 {main}
```

**Comment by Hutchy68** [comment]
Addendum: 

SMW composer.local file for installed SMW extensions.

```
{
	"require": {
		"mediawiki/data-transfer": "*",
		"mediawiki/maps": "5.0.0",
		"mediawiki/semantic-compound-queries": "*",
		"mediawiki/semantic-maps": "*",
		"mediawiki/semantic-media-wiki": "~2.5",
		"mediawiki/semantic-result-formats": "*",
		"mediawiki/semantic-watchlist": "~1.0",
		"mediawiki/user-functions": "*",
		"mediawiki/validator": "*"
		}
}
```

**Comment by mwjames** [comment]
> #0 /home/mw-131/public_html/w/extensions/SemanticWatchlist/src/TableUpdater.php(40): Wikimedia\Rdbms\Database->begin()
#1 /home/mw-131/public_html/w/extensions/SemanticWatchlist/src/MediaWiki/Hooks/UserSaveOptions.php(74): SWL\TableUpdater->updateGroupIdsForUser(integer, array)
#2 /home/mw-131/public_html/w/extensions/SemanticWatchlist/src/MediaWiki/Hooks/UserSaveOptions.php(68): SWL\MediaWiki\Hooks\UserSaveOptions->performUpdate(array)
#3 /home/mw-131/public_html/w/extensions/SemanticWatchlist/src/HookRegistry.php(75): SWL\MediaWiki\Hooks\UserSaveOptions->execute()
#4 /home/mw-131/public_html/w/includes/Hooks.php(177): SWL\HookRegistry->SWL\{closure}(User, array)
#5 /home/mw-131/public_html/w/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#6 /home/mw-131/public_html/w/includes/user/User.php(5516): Hooks::run(string, array)
#7 /home/mw-131/public_html/w/includes/user/User.php(4177): User->saveOptions()
#8 /home/mw-131/public_html/w/extensions/SemanticWatchlist/specials/SpecialSemanticWatchlist.php(159): User->saveSettings()

As the stack trace shows `User->saveOptions` might run (or has opened a transaction) where the transaction isn't closed when the `UserSaveOptions` hook class is executed which collides with `TableUpdater::updateGroupIdsForUser`.

Without being able replicate the error (I haven't installed the extension) I would suggest you encapsulate the `TableUpdater::updateGroupIdsForUser` call into a `Database::onTransactionIdle` allowing transactions to be execute after each other.

[0] https://github.com/wikimedia/mediawiki/blob/master/includes/libs/rdbms/database/IDatabase.php#L1581-L1626

**Comment by tosfos** [comment]
No longer appears to be an issue. Unclear how or when it was fixed. Closing.
