### ISSUE TITLE
Call to undefined function wfRunHooks()

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticWatchlist#93]
Originally reported on [mediawiki.org](https://www.mediawiki.org/wiki/Topic:Vfupftv77h1gvo7p)

**Setup**
- MediaWiki 1.32+
- SWL 1.1.0

**Issue**
`Call to undefined function wfRunHooks()`

**Suggested fix**
Replace `wfRunHooks` with `Hooks::run`

**Comment by kghbln** [comment]
Looks like SMW 3.2.0 will probably kill the suggested fix, not sure though: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4478

**Comment by mwjames** [comment]
> Looks like SMW 3.2.0 will probably kill the suggested fix, not sure though: SemanticMediaWiki/SemanticMediaWiki#4478

No, 4478 is solely for SMW core. As outlined above "Replace wfRunHooks with Hooks::run" remains as task independent and intermediately of what happens thereafter in MW with the `Hooks` class.

**Comment by tosfos** [comment]
Appears to have been fixed in b55c36915e6bd5a9b416a8efcce3ab2ad3dc17c4. Please confirm.
